name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.id || github.ref_name }}
  cancel-in-progress: true
jobs:
  devenv:
    name: Devenv Update
    runs-on: ubuntu-latest
    environment: devenv
    permissions:
      contents: write
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0
      - name: Install Nix
        uses: cachix/install-nix-action@v31.9.0
      - name: Cache
        uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Run update
        run: devenv update
      - name: Commit and push update changes
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          commit_message: 'devenv: Updates Lockfile'
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: write
    if: github.event_name != 'schedule'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0
      - name: Install Nix
        uses: cachix/install-nix-action@v31.9.0
      - name: Cache
        uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Run tests
        run: devenv test
      - name: Commit and push test/format changes
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          commit_message: 'devenv: apply test/format fixes'
  build_typst:
    name: Build Typst Files
    runs-on: ubuntu-latest
    environment: build
    permissions:
      contents: write
    if: github.event_name != 'schedule'
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Nix
        uses: cachix/install-nix-action@v31.9.0
      - name: Cache
        uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Generate
        run: devenv shell typst-build
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: docs/
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_typst
    permissions:
      contents: read
      pages: write
      id-token: write
    if: github.event_name != 'pull_request' && github.event_name != 'schedule'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
